dist: trusty
services:
  - docker
before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/Dockerfile -t pytoda_tests .
script:
  - docker run -it pytoda_tests python3 -m unittest discover -t . -p "test_*py" pytoda
notifications:
  slack:
    secure: 1KuMFoIkpieG6nM5BCJ9IqU+OqZ94sthbQ6UA1JCL9sHXQuDmM9UL0VAERvJsZoh5e3Q5OcKhjfcMkZDkIX1zdlUH+SdTUU1ltTEqS5couOArqo89pk5NfGpM+wIxLJDHr2YxEpzjkMA7mkDiio2GMYxPz6X8w3+Ntml8nMyVCsUtojBQx3IlfcIr+NC2FHz6BfD6QCXLh3DwACTcjX8e8vImr/tFqg1eHrxdDVPjLCHMr0bezQYw0zHWrEokqwv2M5JeH5YLgQ6URV72lTEOBulh7bMPYXca/V5SBY0ZYslwrcQ54m5upFCjnyNpCFkAlNCrYUDE2t5TLGIuFLjqDVNnzIx6ncx/yTAJmd81fesWWV1BnCo+hIWdj2AYznh+GjNvp62p7x8w3zOajkp+W7Tl/ibxigL1wFiocYBMFFt+mFls1Zw0qG/Tbnysq1DdsqQ0ZY0DOdCRsbt5GF1mQuvDFnUFBkoeT6V98I2PYcTq84FEP8v+ogArlOztNXTVUd6cTAOmXT1AwwUVba1UOUmiAq7KNVqO7DGuCwUioMvW8hoOj2P2KbeAhO9p+KF1P5M9iMxlJwXle8gIqLXq/cdzwNqwTReIQvWzLmB/Ec5JeHL8tf0U6FUCqQ3wxjD182jh+RrqDZxiDRtkM74JSJRRNcuCHWbVCXtEG/Ttio=
    on_success: always
    on_failure: always