name: pytoda
channels:
  - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2019.03.1
  - python>=3.6
  - pip
  - pip:
    - numpy == 1.16.1
    - scikit-learn == 0.21.3
    - pandas == 0.25.2
    - torch == 1.0.1
    - diskcache == 4.1.0
    - dill == 0.3.1.1
