on: [push]

jobs:
  conda-tests:
    name: Test with Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8"]
        include:
          - os: ubuntu-latest
            pip_cache_path: ~/.cache/pip
          - os: macos-latest
            pip_cache_path: ~/Library/Caches/pip
          - os: windows-latest
            pip_cache_path: ~\AppData\Local\pip\Cache
    defaults:
      run:
        shell: bash -l {0} # TODO needed for conda?
    env:
      # Increase this value to reset cache if conda.yml and requirements.txt have not changed
      CACHE_NUMBER: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir # defined by conda-incubator/setup-miniconda@v2
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda.yml') }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip_cache_path }}
          key: ${{ runner.os }}-pip--${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}

      - name: Conda environment setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pytoda
          environment-file: conda.yml
          python-version: ${{ matrix.python-version }} # TODO check if this overwrited conda.yml specs
          auto-activate-base: false
          use-only-tar-bz2: true # This needs to be set for caching to work properly!

      - name: Conda list
        run: conda list

      - name: Install pytoda
        run: pip install .

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true

      - name: Format with black
        run: |
          pip install black
          black . --check --diff --color
        continue-on-error: true

      - name: Test coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -s --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        continue-on-error: true
